import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

const manrope = localFont({
  src: './fonts/Manrope.ttf',
  variable: '--font-manrope',
})

export const metadata: Metadata = {
  title: "evnt.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${manrope.variable}`}>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
